export const USER_RANK = {
    CONSTABLE: "CONSTABLE",
    SENIOR_INSPECTOR: "SENIOR INSPECTOR",
    INSPECTOR: "INSPECTOR",
    INVESTIGATING_OFFICIER: "INVESTIGATING OFFICER" 
};

export const USER_ROLE = {
    ADMIN: 'ADMIN', 
    NORMAL_USER: 'USER'
};

export const CASE_PRIORITY = {
    HIGH : "HIGH",
    MEDIUM: "MEDIUM",
    LOW: "LOW"
};

export const CASE_STATUS = {
    PENDING: "PENDING",
    COMPLETED: "COMPLETED",
    EXPIRED: "EXPIRED"
};

export const STATUS = {
    OK: 200,
    INTERNAL_SERVER_ERROR: 500,
    CREATED: 201,
    UNAUTHORISED: 401,
    NOT_FOUND: 404,
    BAD_REQUEST: 400,
    FORBIDDEN: 403,
    UNPROCESSABLE_ENTITY: 422,
    GONE: 410,
    PAYMENT_REQUIRED: 402
};

export const OTP_PURPOSE = {
    SIGNIN: "SIGNIN",
    SIGNUP: "SIGNUP",
    RESET_PASSWORD: "RESET_PASSWORD"
}

export const REGEX = {
    EMAIL: /^[A-Za-z0-9._+%-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/
}